version: 2.1

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - clippy
jobs:
  build:
    docker:
      - image: circleci/rust:latest
    environment:
      TZ: "/usr/share/zoneinfo/your/location"
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Check formatting
          command: cargo fmt -- --check
      - run:
          name: Stable Build
          command: cargo build --features "nalgebra-bindings ndarray-bindings"
      - run:
          name: Test
          command: cargo test --features "nalgebra-bindings ndarray-bindings"
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
  clippy:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Install cargo clippy
          command: rustup component add clippy
      - run:
          name: Run cargo clippy
          command: cargo clippy --all-features -- -Drust-2018-idioms -Dwarnings
